/* SyslogAgentSharedContants.h 
* single file to collect constants that must be shared between
* Syslog Agent apps (such as the config app)
* unfortunately this file still must be manually synched to
* the config app but at least having them in this single point
* reduces the chances of mismatch
*/

#define SYSLOGAGENT_CURRENT_VERSION                 L"6.30.2.0"
#define SYSLOGAGENT_CURRENT_CONFIG_VERSION		    L"6.30.0.0"

#define SYSLOGAGENT_DEFAULT_FACILITY				20
#define SYSLOGAGENT_DEFAULT_SEVERITY				8
#define SYSLOGAGENT_DEFAULT_PRIMARY_HOST			L""
#define SYSLOGAGENT_DEFAULT_SECONDARY_HOST			L""
#define SYSLOGAGENT_DEFAULT_USE_FORWARDER			(false)
#define SYSLOGAGENT_DEFAULT_FORWARDER_DEST			L""
#define SYSLOGAGENT_DEFAULT_UDP_FWD_PORT_S			L""
#define SYSLOGAGENT_DEFAULT_TCP_FWD_PORT_S			L""
#define SYSLOGAGENT_DEFAULT_SUFFIX					L""
#define SYSLOGAGENT_DEFAULT_DEBUG_LOG_FILENAME		L""
#define SYSLOGAGENT_DEFAULT_TAIL_FILENAME			L""
#define SYSLOGAGENT_DEFAULT_TAIL_PROGRAMNAME		L""
#define SYSLOGAGENT_DEFAULT_POLL_INTERVAL			2
#define SYSLOGAGENT_USER_AGENT	        			L"LZ Syslog Agent/" SYSLOGAGENT_CURRENT_VERSION
#define SYSLOGAGENT_HTTP_API_PATH                   L"/incoming"
#define SYSLOGAGENT_LOGZILLA_VERSION_PATH           L"/version"
#define SYSLOGAGENT_DEFAULT_BATCH_INTERVAL          1000


#define SYSLOGAGENT_SEVERITY_EMERGENCY			0
#define SYSLOGAGENT_SEVERITY_ALERT				1
#define SYSLOGAGENT_SEVERITY_CRITICAL			2
#define SYSLOGAGENT_SEVERITY_ERROR				3
#define SYSLOGAGENT_SEVERITY_WARNING			4
#define SYSLOGAGENT_SEVERITY_NOTICE				5
#define SYSLOGAGENT_SEVERITY_INFORMATIONAL		6
#define SYSLOGAGENT_SEVERITY_DEBUG				7
#define SYSLOGAGENT_SEVERITY_DYNAMIC			8

#define SYSLOGAGENT_FACILITY_KERNEL				0
#define SYSLOGAGENT_FACILITY_USER				1
#define SYSLOGAGENT_FACILITY_MAIL				2
#define SYSLOGAGENT_FACILITY_SYSTEM				3
#define SYSLOGAGENT_FACILITY_SECAUTH			4
#define SYSLOGAGENT_FACILITY_SYSLOGD			5
#define SYSLOGAGENT_FACILITY_LPRINTER			6
#define SYSLOGAGENT_FACILITY_NETNEWS			7
#define SYSLOGAGENT_FACILITY_UUCP				8
#define SYSLOGAGENT_FACILITY_CLOCK				9
#define SYSLOGAGENT_FACILITY_SECAUTH2			10
#define SYSLOGAGENT_FACILITY_FTP				11
#define SYSLOGAGENT_FACILITY_NTP				12
#define SYSLOGAGENT_FACILITY_LOGAUDIT			13
#define SYSLOGAGENT_FACILITY_LOGALERT			14
#define SYSLOGAGENT_FACILITY_CLOCK2				15
#define SYSLOGAGENT_FACILITY_LOCALUSE0			16
#define SYSLOGAGENT_FACILITY_LOCALUSE1			17
#define SYSLOGAGENT_FACILITY_LOCALUSE2			18
#define SYSLOGAGENT_FACILITY_LOCALUSE3			19
#define SYSLOGAGENT_FACILITY_LOCALUSE4			20
#define SYSLOGAGENT_FACILITY_LOCALUSE5			21
#define SYSLOGAGENT_FACILITY_LOCALUSE6			22
#define SYSLOGAGENT_FACILITY_LOCALUSE7			23

#define SYSLOGAGENT_REGISTRYKEY_MAIN							L"SOFTWARE\\LogZilla\\SyslogAgent"
#define SYSLOGAGENT_REGISTRYKEY_CHANNELS						L"SOFTWARE\\LogZilla\\SyslogAgent\\Channels"
#define SYSLOGAGENT_REGISTRYKEY_CONFIGVERSION					L"ConfigVersion"
#define SYSLOGAGENT_REGISTRYKEY_INCLUDE_VS_IGNORE_EVENTIDS      L"IncludeVsIgnoreEventIds"
#define SYSLOGAGENT_REGISTRYKEY_EVENT_ID_FILTER					L"EventIDFilterList"
#define SYSLOGAGENT_REGISTRYKEY_ONLY_WHILE_RUNNING              L"OnlyWhileRunning"
#define SYSLOGAGENT_REGISTRYKEY_EVENT_LOG_POLL_INTERVAL			L"EventLogPollInterval"
#define SYSLOGAGENT_REGISTRYKEY_FORWARD_TO_SECONDARY			L"ForwardToMirror"
#define SYSLOGAGENT_REGISTRYKEY_LOOKUP_ACCOUNTS					L"LookupAccountSID"
#define SYSLOGAGENT_REGISTRYKEY_INCLUDE_KEY_VALUE_PAIRS			L"IncludeKeyValuePairs"
#define SYSLOGAGENT_REGISTRYKEY_SECONDARY_PORT					L"SendToBackupPort"
#define SYSLOGAGENT_REGISTRYKEY_PRIMARY_HOST					L"Syslog"
#define SYSLOGAGENT_REGISTRYKEY_SECONDARY_HOST					L"Syslog1"
#define SYSLOGAGENT_REGISTRYKEY_PRIMARY_USE_TLS					L"PrimaryUseTLS"
#define SYSLOGAGENT_REGISTRYKEY_SECONDARY_USE_TLS				L"SecondaryUseTLS"
#define SYSLOGAGENT_REGISTRYKEY_FACILITY						L"Facility"
#define SYSLOGAGENT_REGISTRYKEY_SEVERITY						L"Severity"
#define SYSLOGAGENT_REGISTRYKEY_SUFFIX							L"Suffix"
#define SYSLOGAGENT_REGISTRYKEY_DEBUG_LEVEL_SETTING				L"DebugLevel"
#define SYSLOGAGENT_REGISTRYKEY_DEBUG_LOG_FILE					L"DebugLogFile"
#define SYSLOGAGENT_REGISTRYKEY_TAIL_FILENAME					L"TailFilename"
#define SYSLOGAGENT_REGISTRYKEY_TAIL_PROGRAM_NAME				L"TailProgramName"
#define SYSLOGAGENT_REGISTRYKEY_CHANNEL_ENABLED					L"Enabled"
#define SYSLOGAGENT_REGISTRYKEY_CHANNEL_BOOKMARK				L"Bookmark"
#define SYSLOGAGENT_REGISTRYKEY_INITIAL_SETUP_FILE				L"InitialSetupRegFile"
#define SYSLOGAGENT_REGISTRYKEY_SETUP_TEMP_RESTORE				L"SetupRestore"
#define SYSLOGAGENT_REGISTRYKEY_SETUP_PRIMARY_TLS_FILENAME		L"PrimaryTlsFileName"
#define SYSLOGAGENT_REGISTRYKEY_SETUP_SECONDARY_TLS_FILENAME	L"SecondaryTlsFileName"
#define SYSLOGAGENT_REGISTRYKEY_PRIMARY_LOGZILLA_API_KEY        L"PrimaryLogZillaApiKey"
#define SYSLOGAGENT_REGISTRYKEY_SECONDARY_LOGZILLA_API_KEY      L"SecondaryLogZillaApiKey"
#define SYSLOGAGENT_REGISTRYKEY_BATCH_INTERVAL                  L"BatchInterval"
#define SYSLOGAGENT_REGISTRYKEY_PRIMARY_LOGFORMAT               L"PrimaryLogFormat"
#define SYSLOGAGENT_REGISTRYKEY_SECONDARY_LOGFORMAT             L"SecondaryLogFormat"
#define SYSLOGAGENT_CERT_FILENAME_PRIMARY						L"primary.pfx"
#define SYSLOGAGENT_CERT_FILENAME_SECONDARY						L"secondary.pfx"

#define SYSLOGAGENT_MAX_SUFFIX_LENGTH							1000
#define SYSLOGAGENT_SENDER_MAINLOOP_DURATION                    1000

#define SYSLOGAGENT_LOGFORMAT_DETECT                            0
#define SYSLOGAGENT_LOGFORMAT_JSONPORT                          1
#define SYSLOGAGENT_LOGFORMAT_HTTPPORT                          2
#define SYSLOGAGENT_LOGFORMAT_LZ_VERSION_HTTP                   "6.34"
